### ISSUE TITLE
ST3 issue

### ISSUE THREAD

**Issue by sglyon** [dkleinsmann/sublime_sequential_build#1]
First, I am excited about this package. I have been wanting something like this for a while, but haven't gotten around to doing it personally. 

I am trying to build a latex file that uses pythontex. 

The build sequence is the following:
1. `latex tex_source.tex'
2. `pythontex.py tex_source.tex'
3. `latex tex_source.tex'

When I run those commands in that order on the command line it does exactly what I would expect. 

I have created the following pythontex.sublime-build file:

``` json
{
    "name": "pythontex",
    "target": "sequential_builder",
    "build_sequence":
    [
        {
            "cmd": ["latex", "{file}"]
        },
        {
            "cmd": ["pythontex.py", "{file}"]
        },
        {
            "cmd": ["latex", "{file}"]
        }
    ]
}
```

I have gone to the menu and selected pythontex from the list of build systems, but when I try to bulid nothing shows up. If I inspect the internal sublime python interpreter I see the following message:

`Unable to find target command: sequential_builder`

What can I do to get this working? Thank you

Oh and when I do Package Control: List Packages from the command palette SequentialBuilder is in the list.

**Comment by sglyon** [comment]
I just read this:

> Warning: The build system variables (ie $project_path) cannot be used in individual build steps. The reason for this is that they are resolved outside of the python plugin framework.

Does this mean that I cannot execute this type of build because it is dependent on the file name?

**Comment by dkleinsmann** [comment]
I'm afraid you're right about not being able to use "$file" yet.
However you have given me an idea for a workaround which I will have a crack at tomorrow.

Shifting track to the "Unable to find target command: sequential_builder", Could you perhaps send me a larger chunk of log text.

Thanks

**Comment by sglyon** [comment]
I am not sure if you are planning on supporting sublime 3, but the real issue is some python 2 to python 3 incompatibility things. When I start a fresh session of sublime and look at the console this is what I see:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/sglyon/Library/Application Support/Sublime Text 3/Packages/SequentialBuilder/sequential_builder.py", line 10, in <module>
    ExecCommand = getattr( __import__("exec", fromlist="ExecCommand"),
ImportError: No module named 'exec'
```

The other problem that I have found so far is changing [this line](https://github.com/dkleinsmann/sublime_sequential_build/blob/master/sequential_builder.py#L96) from the following:

``` python
print "Build Step (%d): %s" % (index+1, step_args)
```

To the following (Just using the python 2 and python 3 compatible print function instead of the python 2 specific print statement):

``` python
print("Build Step (%d): %s" % (index+1, step_args))
```

**Comment by dkleinsmann** [comment]
I've pushed an update now which I hope will work for you.
And please let me know if it doesn't and I'll see what I can do.

**Comment by sglyon** [comment]
Still not quite there...

**Comment by sglyon** [comment]
In python 3 the `dict.has_key` method has been removed.

The safe way to do this (for both python2 and python3) is to use the following:

``` python
x = {1:'1', 2:'2'}
if 1 in x:  # Do this instead of `x.has_key(1)`
    do_something()
```

Also, there is a bug in [these lines](https://github.com/dkleinsmann/sublime_sequential_build/blob/master/sequential_builder.py#L199-L203)

Right now they say 

``` python
if step_args.has_key( 'working_dir' ) and \
   not os.path.isabs( step_args['working_dir'] ):
    step_args['working_dir'] = os.path.join(
        args['working_dir'],
        step_args['working_dir'] )
```

When they should say 

``` python
if 'working_dir' in step_args:
    if not os.path.isabs( step_args['working_dir'] ):
        step_args['working_dir'] = os.path.join(
        args['working_dir'],
        step_args['working_dir'] )
```

The problem was putting them in a compound statement (using `and`) and trying to access `step_args['working_dir']` when `step_args` might not have that key. 

A similar bug is in [this line](https://github.com/dkleinsmann/sublime_sequential_build/blob/master/sequential_builder.py#L207), which currently reads

``` python
args['working_dir'] = os.path.abspath(args['working_dir'])
```

but should instead check to make sure that `working_dir` is a key for `args` like so:

``` python
if 'working_dir' in args:
    args['working_dir'] = os.path.abspath(args['working_dir'])
```

**Comment by sglyon** [comment]
Even after making all those changes, I get the following error when trying to use my sequential build (note this is printed in the console and I have remove the actual path):

```
__init__() got an unexpected keyword argument 'name'
[cmd: ['latex', '/path/to/file/test.tex']]
[dir: /path/to/file]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sglyon/bin]
[Finished]
```

**Comment by sglyon** [comment]
I misspoke in the previous comment. That message was printed in the build results window, not the sublime python console.

**Comment by dkleinsmann** [comment]
Thanks for the pointers wrt "has_key()". Curious I did some playing with ST3 in a ubuntu VM but that didn't give me any warnings about has_key not existing. Never mind, I'll add those changes shortly.

I did have a problem under windows, where adding the "shell": true option to a step fixed my problem.

**Comment by sglyon** [comment]
No problem. I am actually a python programmer, but haven't taken the time to learn the sublime API.

Anyway, I tried adding `"shell": true` to the sublime-build file and am having no luck. 

Do you know where we are creating an object and trying to pass the keyword argument `'name'`? I haven't been able to find it in the sublime_sequential_build.py file.

**Comment by ci70** [comment]
Can you update this for ST3? Thank you.
